stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: recycle-project
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

test:
  stage: test
  tags:
    - recycle-runner
  script:
    - echo "Test stage en runner propio"
  only:
    - main

build:
  stage: build
  tags:
    - recycle-runner
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker save $IMAGE_NAME:$IMAGE_TAG | gzip > image.tar.gz
  artifacts:
    paths:
      - image.tar.gz
    expire_in: 1 hour
  only:
    - main

deploy:
  stage: deploy
  tags:
    - recycle-runner
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - ssh-keyscan -H $DROPLET_IP >> ~/.ssh/known_hosts
  script:
    - scp image.tar.gz root@$DROPLET_IP:/tmp/
    - ssh root@$DROPLET_IP "
        docker load < /tmp/image.tar.gz &&
        docker stop recycle-app || true &&
        docker rm recycle-app || true &&
        docker run -d --name recycle-app -p 8501:8501 -p 50051:50051 $IMAGE_NAME:$IMAGE_TAG &&
        rm /tmp/image.tar.gz
      "
  only:
    - main