test:
  stage: test
  tags:
    - recycle-runner
  before_script:
    - sudo apt-get update -qq && sudo apt-get install -y python3-pip python3-venv
    - pip3 install -r requirements.txt
  script:
    - pip3 install pytest
    - pytest tests/ -v
  only:
    - main